// Placeholder Activity_Feed for a student profile.
//
// The real feed lists the most recent Activity_Events generated by an Account
// (forum replies, RSVPs, memberships joined, public wall posts). Those events
// are produced by later tranches; for now this renders an accessible empty
// state so the public profile page (Req 6.1, 6.2) has a complete, labelled
// section in place.
//
// Requirements: 6.2 (Activity_Feed is part of the profile), 6.3 (chronological
// list — empty for now)
// Design: Frontend layout segments

export interface ActivityFeedProps {
  /** Display name of the profile owner, used for accessible labelling. */
  displayName: string;
}

export default function ActivityFeed({ displayName }: ActivityFeedProps) {
  return (
    <section aria-labelledby="activity-feed-heading" className="mt-8">
      <h2
        id="activity-feed-heading"
        className="text-lg font-bold text-gray-900"
      >
        Activity
      </h2>
      <div
        role="status"
        className="mt-3 rounded-2xl border border-dashed border-gray-300 bg-gray-50 px-6 py-10 text-center"
      >
        <p className="text-sm text-gray-600">
          {displayName} has no activity yet.
        </p>
        <p className="mt-1 text-xs text-gray-500">
          Replies, RSVPs, and posts will show up here.
        </p>
      </div>
    </section>
  );
}
