// This file is generated by `npm run gen:types`
// (supabase gen types --lang=typescript --linked --schema public > src/lib/data/types.ts).
//
// Until the first generation runs against a live local database, this
// placeholder keeps imports of `Database` resolving. Do not hand-edit the
// generated output; re-run the script instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
